/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package khorrth.discovery;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int broken_tree=0x7f020001;
        public static final int brown_grass=0x7f020002;
        public static final int carl=0x7f020003;
        public static final int carl_r=0x7f020004;
        public static final int chest=0x7f020005;
        public static final int decorative_tree=0x7f020006;
        public static final int demo_map_object=0x7f020007;
        public static final int flover=0x7f020008;
        public static final int green_grass=0x7f020009;
        public static final int k=0x7f02000a;
        public static final int tree_stump=0x7f02000b;
        public static final int zombie=0x7f02000c;
    }
    public static final class string {
        public static final int DEFAULT_MODEL_FRAGMENT_SHADER_CODE=0x7f030001;
        public static final int DEFAULT_MODEL_VERTEX_SHADER_CODE=0x7f030000;
    }
}
